mobile_base_controller:
  # Wheel separation and radius multipliers for tiago_47
  wheel_separation_multiplier:   1.0097822
  left_wheel_radius_multiplier:  0.98960406
  right_wheel_radius_multiplier: 0.98813198
